/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TheBeachClub;

import Project1.GuestUI;
import java.awt.Color;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author triciaamber
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setColor(guestTab);
        resetColor(new JPanel[]{roomTab,resTab,spaTab,empTab});
        
        
        populateGuestTable(); // Call this method to populate the GuestTable when the form is initialized

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        Parent = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        guestTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        roomTab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        resTab = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        spaTab = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        empTab = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TitlePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        guestPage = new javax.swing.JPanel();
        GuestButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GuestTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        guestIDTextField = new javax.swing.JTextField();
        guestFirstNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        resPage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        reservationUI1 = new TheBeachClub.ReservationUI();
        roomsPage = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        roomUI1 = new TheBeachClub.RoomUI();
        spaPage = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        empPage = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Parent.setBackground(new java.awt.Color(153, 153, 153));
        Parent.setForeground(new java.awt.Color(255, 255, 255));
        Parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(237, 237, 237));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guestTab.setBackground(new java.awt.Color(237, 237, 237));
        guestTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guestTabMousePressed(evt);
            }
        });

        jLabel5.setText("Guests");

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/triciaamber/Documents/TheBeachClub/guest.png")); // NOI18N
        jLabel1.setText("  ");

        javax.swing.GroupLayout guestTabLayout = new javax.swing.GroupLayout(guestTab);
        guestTab.setLayout(guestTabLayout);
        guestTabLayout.setHorizontalGroup(
            guestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guestTabLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        guestTabLayout.setVerticalGroup(
            guestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guestTabLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(guestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18))
        );

        sidepanel.add(guestTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 200, -1));

        roomTab.setBackground(new java.awt.Color(237, 237, 237));
        roomTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roomTabMousePressed(evt);
            }
        });

        jLabel7.setText("Rooms");

        javax.swing.GroupLayout roomTabLayout = new javax.swing.GroupLayout(roomTab);
        roomTab.setLayout(roomTabLayout);
        roomTabLayout.setHorizontalGroup(
            roomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomTabLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomTabLayout.setVerticalGroup(
            roomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        sidepanel.add(roomTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 200, -1));

        resTab.setBackground(new java.awt.Color(237, 237, 237));
        resTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resTabMousePressed(evt);
            }
        });

        jLabel8.setText("Reservations");

        javax.swing.GroupLayout resTabLayout = new javax.swing.GroupLayout(resTab);
        resTab.setLayout(resTabLayout);
        resTabLayout.setHorizontalGroup(
            resTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resTabLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel8)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        resTabLayout.setVerticalGroup(
            resTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        sidepanel.add(resTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, -1, -1));

        spaTab.setBackground(new java.awt.Color(237, 237, 237));
        spaTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spaTabMousePressed(evt);
            }
        });

        jLabel9.setText("Spa");

        javax.swing.GroupLayout spaTabLayout = new javax.swing.GroupLayout(spaTab);
        spaTab.setLayout(spaTabLayout);
        spaTabLayout.setHorizontalGroup(
            spaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spaTabLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        spaTabLayout.setVerticalGroup(
            spaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spaTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        sidepanel.add(spaTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 251, 200, -1));

        empTab.setBackground(new java.awt.Color(237, 237, 237));
        empTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                empTabMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                empTabMouseReleased(evt);
            }
        });

        jLabel10.setText("Employees");

        javax.swing.GroupLayout empTabLayout = new javax.swing.GroupLayout(empTab);
        empTab.setLayout(empTabLayout);
        empTabLayout.setHorizontalGroup(
            empTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empTabLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        empTabLayout.setVerticalGroup(
            empTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        sidepanel.add(empTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 307, 200, -1));

        Parent.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 570));

        TitlePanel.setBackground(new java.awt.Color(245, 245, 245));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setText("The Beach Club");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        Parent.add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 710, 80));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guestPage.setBackground(new java.awt.Color(255, 255, 255));

        GuestButton.setText("Guest");
        GuestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuestButtonMouseClicked(evt);
            }
        });

        GuestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(GuestTable);

        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addButtonMousePressed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel13.setText("First Name");

        javax.swing.GroupLayout guestPageLayout = new javax.swing.GroupLayout(guestPage);
        guestPage.setLayout(guestPageLayout);
        guestPageLayout.setHorizontalGroup(
            guestPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guestPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guestPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guestPageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addGap(61, 61, 61))
                    .addGroup(guestPageLayout.createSequentialGroup()
                        .addGroup(guestPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guestPageLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(guestPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(guestFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guestIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(GuestButton)
                            .addGroup(guestPageLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel13)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        guestPageLayout.setVerticalGroup(
            guestPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guestPageLayout.createSequentialGroup()
                .addGroup(guestPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guestPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GuestButton)
                        .addGap(18, 18, 18)
                        .addGroup(guestPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guestPageLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestPageLayout.createSequentialGroup()
                                .addComponent(guestIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guestFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(addButton))
                    .addGroup(guestPageLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        content.add(guestPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        resPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Reservations");

        javax.swing.GroupLayout resPageLayout = new javax.swing.GroupLayout(resPage);
        resPage.setLayout(resPageLayout);
        resPageLayout.setHorizontalGroup(
            resPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resPageLayout.createSequentialGroup()
                .addGroup(resPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resPageLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3))
                    .addGroup(resPageLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(reservationUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        resPageLayout.setVerticalGroup(
            resPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resPageLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        content.add(resPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        roomsPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Rooms");

        javax.swing.GroupLayout roomsPageLayout = new javax.swing.GroupLayout(roomsPage);
        roomsPage.setLayout(roomsPageLayout);
        roomsPageLayout.setHorizontalGroup(
            roomsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomsPageLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addContainerGap(571, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomsPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roomUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roomsPageLayout.setVerticalGroup(
            roomsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomsPageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        content.add(roomsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        spaPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Spa Appointments");

        javax.swing.GroupLayout spaPageLayout = new javax.swing.GroupLayout(spaPage);
        spaPage.setLayout(spaPageLayout);
        spaPageLayout.setHorizontalGroup(
            spaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spaPageLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        spaPageLayout.setVerticalGroup(
            spaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spaPageLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        content.add(spaPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        empPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Employees");

        javax.swing.GroupLayout empPageLayout = new javax.swing.GroupLayout(empPage);
        empPage.setLayout(empPageLayout);
        empPageLayout.setHorizontalGroup(
            empPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPageLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        empPageLayout.setVerticalGroup(
            empPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel11)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        content.add(empPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Parent.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 640, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void populateGuestTable() {
    DefaultTableModel model = (DefaultTableModel) GuestTable.getModel();
    model.setRowCount(0); // Clear existing rows
    
    try {
        // Establish database connection
        Connection connection = DBConnection.getConnection();
        Statement statement = connection.createStatement();
        ResultSet resultSet = statement.executeQuery("SELECT guestID, guest_firstName, guest_lastName, guest_email, guest_phone FROM Guest");
        
        while (resultSet.next()) {
            int guestID = resultSet.getInt("guestID");
            String firstName = resultSet.getString("guest_firstName");
            String lastName = resultSet.getString("guest_lastName");
            String email = resultSet.getString("guest_email");
            String phone = resultSet.getString("guest_phone");
            
            model.addRow(new Object[]{guestID, firstName, lastName, email, phone});
        }
        
        resultSet.close();
        statement.close();
        connection.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}


    
    private void guestTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestTabMousePressed
        // TODO add your handling code here:
        setColor(guestTab);
        resetColor(new JPanel[]{roomTab,resTab,spaTab,empTab});
        
        guestPage.setVisible(true);
        resPage.setVisible(false);
        roomsPage.setVisible(false);
        spaPage.setVisible(false);
        empPage.setVisible(false);
    }//GEN-LAST:event_guestTabMousePressed

    private void resTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resTabMousePressed
        // TODO add your handling code here:
        setColor(resTab);
        resetColor(new JPanel[]{roomTab,guestTab,spaTab,empTab});
        
        guestPage.setVisible(false);
        resPage.setVisible(true);
        roomsPage.setVisible(false);
        spaPage.setVisible(false);
        empPage.setVisible(false);
    }//GEN-LAST:event_resTabMousePressed

    private void roomTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomTabMousePressed
        // TODO add your handling code here:
        setColor(roomTab);
        resetColor(new JPanel[]{resTab,guestTab,spaTab,empTab});
        
        guestPage.setVisible(false);
        resPage.setVisible(false);
        roomsPage.setVisible(true);
        spaPage.setVisible(false);
        empPage.setVisible(false);
    }//GEN-LAST:event_roomTabMousePressed

    private void spaTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spaTabMousePressed
        // TODO add your handling code here:
        setColor(spaTab);
        resetColor(new JPanel[]{roomTab,guestTab,resTab,empTab});
        
        guestPage.setVisible(false);
        resPage.setVisible(false);
        roomsPage.setVisible(false);
        spaPage.setVisible(true);
        empPage.setVisible(false);
    }//GEN-LAST:event_spaTabMousePressed

    private void empTabMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empTabMouseReleased
        // TODO add your handling code here:
        setColor(empTab);
        resetColor(new JPanel[]{roomTab,guestTab,spaTab,resTab});
    }//GEN-LAST:event_empTabMouseReleased

    private void empTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empTabMousePressed
        // TODO add your handling code here:
        
        guestPage.setVisible(false);
        resPage.setVisible(false);
        roomsPage.setVisible(false);
        spaPage.setVisible(false);
        empPage.setVisible(true);
    }//GEN-LAST:event_empTabMousePressed

    private void GuestButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestButtonMouseClicked
        // TODO add your handling code here:
        // Create an instance of the GuestUI panel
    // Create an instance of the GuestUI frame
    GuestUI guestUI = new GuestUI();
    
    // Set the GuestUI frame visible
    guestUI.setVisible(true);
    
    // Hide the current Home frame (optional)
    this.setVisible(false);
    }//GEN-LAST:event_GuestButtonMouseClicked

    private void addButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMousePressed
        // TODO add your handling code here:
        
        // Get the values from the text fields
    int guestID = Integer.parseInt(guestIDTextField.getText());
    String firstName = guestFirstNameTextField.getText();
//    String lastName = lastNameTextField.getText();
//    String email = emailTextField.getText();
//    String phone = phoneTextField.getText();

    
    // Create a new Guest object
    Guest guest = new Guest(guestID, firstName, "", "", "");
    
    // Add the guest to the database
    GuestManager.addGuest(guest);
    
    // Populate the table with the updated guest list
    populateGuestTable();
    }//GEN-LAST:event_addButtonMousePressed
       int xy, xx;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(219, 219, 219));
    }
    
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(237,237,237));     
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuestButton;
    private javax.swing.JTable GuestTable;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel content;
    private javax.swing.JPanel empPage;
    private javax.swing.JPanel empTab;
    private javax.swing.JTextField guestFirstNameTextField;
    private javax.swing.JTextField guestIDTextField;
    private javax.swing.JPanel guestPage;
    private javax.swing.JPanel guestTab;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel resPage;
    private javax.swing.JPanel resTab;
    private TheBeachClub.ReservationUI reservationUI1;
    private javax.swing.JPanel roomTab;
    private TheBeachClub.RoomUI roomUI1;
    private javax.swing.JPanel roomsPage;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel spaPage;
    private javax.swing.JPanel spaTab;
    // End of variables declaration//GEN-END:variables
}
